### ISSUE TITLE
Introduce `clean` command

### ISSUE THREAD

**Issue by hurricup** [skaji/perl-install#2]
I'm using plenv alongside with perlbrew and asdf for my CI tests and using caches. And when perlbrew/asdf caches are about 19 mb, plenv cache is 77mb.

Would be nice to have a way to solve this in a smarter way than `rm -Rf ./.plenv/cache`

`perlbrew` has a `clean` command and `asdf` presumably store this installation cache somewhere else.

**Comment by skaji** [comment]
It seems that you are using Perl-Build, not perl-install, right?

**Comment by hurricup** [comment]
Oh god, this is embarrassing :) Seems so :D
Not sure how I missed that :D
